import com.mtnfog.entity.Entity;
import com.mtnfog.idyl.sdk.rulesengine.drools.model.EntitiesHolder;
import com.mtnfog.idyl.sdk.eql.filters.EqlFilters;
import com.amazonaws.regions.RegionUtils;

// This is a sample rule that uses an EQL query as a condition.

rule "Sample EQL Rule"
	
	when
			
		$holder : EntitiesHolder()
		$entity : Entity() from $holder.entities
		
		eval(EqlFilters.isMatch($entity, "select * from entities where text = \"George Washington\""))
		
	then

		System.out.println("Match!");
		
end
